---
- name: Build and run the backend container
  block:
    - name: Build the backend image
      docker_image:
        name: "yolo-backend:v1.0.0"
        build:
          context: "./backend"
        state: present
      tags: backend

    - name: Run the backend container
      docker_container:
        name: backend
        image: "yolo-backend"
        ports: "5000:5000"
        volumes: "./backend:/app/backend"
        depends_on:
          - mongo
        networks:
          - name: "yolo-network"
        state: started
      tags: backend
  tags: backend
