version: '3'

services:
  client:
    image: yolo-client:v1.0.0
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./client:/app/client
    networks:
      - yolo-network

  backend:
    image: yolo-backend:v1.0.0
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app/backend
    networks:
      - yolo-network

  mongo:
    image: mongo:jammy
    ports:
      - "27018:27017"
    volumes:
      - ./mongodb-data:/data/db
    networks:
      - yolo-network

networks:
  yolo-network:
    driver: bridge

  

