---
- name: Deploy Docker Containers
  hosts: 127.0.0.1
  become: true

  tasks:
    - name: Include variables
      include_vars: variables.yml
  roles:
    - client
    - backend
    - mongo
    - common
