---
- name: Deploy Docker Containers
  hosts: localhost
  tasks:
    - name: Include variables
      include_vars: variables.yml

    - name: Set up client container
      include_role:
        name: client
      tags: client

    - name: Set up backend container
      include_role:
        name: backend
      tags: backend

    - name: Set up mongo container
      include_role:
        name: mongo
      tags: mongo
