---
- name: Deploy Docker Containers
  hosts: localhost
  become: true

  tasks:
    - name: Include variables
      include_vars: variables.yml

    - name: Set up client container
      include_role:
        name: client
      tags: client

    - name: Set up backend container
      include_role:
        name: backend
      tags: backend

    - name: Set up mongoDB
      include_role:
        name: mongo
      tags: mongo
