---
- name: Clone the repository from GitHub
  git:
    repo: https://github.com/alphaWomanMuthonks/yolo.git
    dest: "{{ playbook_dir}}/backend"
  become: true

- name: Install Node.js and npm
  apt:
    name: 
      - nodejs
      - npm
    state: present  
  become: true
  when: ansible_distribution == "Ubuntu" 

- name: Start backend
  service: 
    name: npm start
  become: true

- name: Pull backend Docker image
  docker_image:
    name: joymalanga/yolo-backend:v1.0.0
    source: pull
  register: backend_image
  tags:
    - client

- name: build backend container
  docker_container:
    name: yolo-backend-container
    image: joymalanga/yolo-backend:v1.0.0
    state: started
    volumes:
      - ./backend:/app/backend/
    ports:
      - '5000:5000'
    networks:
      - name: yolo_network
    env:
      MONGO_URI: 'mongodb://yolo-database-container:27017/jammy'
  tags:
    - backend
