---
- name: Clone the repository from GitHub
  git:
    repo: https://github.com/alphaWomanMuthonks/yolo.git
    dest: "{{ backend_dir }}"
  become: true

- name: Install Dependencies for backend
  shell: npm install
  args:
    chdir: "{{playbook_dir}}/backend"

- name: Start {{ app_name }} Client App
  shell: npm start
  args:
    chdir: "{{ backend_dir }}"
