
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: joymalanga/yolo-frontend:v1.0.0
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: frontend-volume
          mountPath: /app/frontend
  volumes:
  - name: frontend-volume
    persistentVolumeClaim:
      claimName: frontend-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: joymalanga/yolo-frontend:v1.0.0
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: backend-volume
          mountPath: /app/backend
  volumes:
  - name: backend-volume
    persistentVolumeClaim:
      claimName: backend-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    type: LoadBalancer
