---
- name: Update packages
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Start Docker service
  service:
    name: docker
    state: started

- name: Create Custom Bridge Network
  docker_network:
    name: yolo_network
    state: present
    attachable: true
  tags:
    - network