---
- name: Clone the repository from GitHub
  git:
    repo: https://github.com/alphaWomanMuthonks/yolo.git
    dest: "{{playbook_dir}}/client"
  become: true

- name: Install Dependencies for backend
  shell: npm install
  args:
    chdir: "{{playbook_dir}}/client"

- name: Start {{ app_name }} Client App
  shell: npm start
  args:
    chdir: "{{playbook_dir}}/client"


