# ---
# - name: Clone the repository from GitHub
#   git:
#     repo: https://github.com/alphaWomanMuthonks/yolo.git
#     dest: "{{playbook_dir}}/client"
#   become: true

# - name: Install Dependencies for client
#   shell: npm install
#   args:
#     chdir: "{{playbook_dir}}/client"

# - name: Start Client 
#   shell: npm start
#   args:
#     chdir: "{{playbook_dir}}/client"
---
- name: Clone the repository from GitHub
  git:
    repo: https://github.com/alphaWomanMuthonks/yolo.git
    dest: "{{playbook_dir}}/client"
  become: true

- name: Install Node.js and npm
  apt:
    name: 
      - nodejs
      - npm
    state: present  
  become: true
  when: ansible_distribution == "Ubuntu"  

- name: Start Client
  service: 
    name: npm start
  become: true

- name: Build client docker image
  docker_image:
    name: joymalanga/yolo-client:v1.0.0
    source: build
    build:
      path: '{{playbook_dir}}/client'
  register: client_image
  tags:
    - frontend

- name: build client docker container
  docker_container:
    name: yolo-client-container
    image: joymalanga/yolo-client:v1.0.0
    state: started
    volumes:
      - ./client:/app/client/
    ports:
      - '3000:3000'
    networks:
      - name: yolo_network
    network_mode: bridge
