---
- name: Build and run the client container
  block:
    - name: Build the client image
      docker_image:
        name: "yolo-client:v1.0.0"
        build:
          context: "./client"
        state: present
      tags: client

    - name: Run the client container
      docker_container:
        name: client
        image: "yolo-client"
        ports: "3000:3000"
        volumes: "./client:/app/client"
        depends_on:
          - backend
        networks:
          - name: "yolo-network"
        state: started
      tags: client
  tags: client