
---
- name: Clone the repository from GitHub
  git:
    repo: https://github.com/alphaWomanMuthonks/yolo.git
    dest: "{{playbook_dir}}/client"
  become: true

- name: Install Node.js and npm
  apt:
    name: 
      - nodejs
      - npm
    state: present  
  become: true
  when: ansible_distribution == "Ubuntu"  

- name: Start Client
  service: 
    name: npm start
  become: true
  
- name: Ensure Docker library is available
  pip:
    name: docker
    state: present
    become: yes  # This may be necessary to install packages
    ansible_python_interpreter: /usr/bin/python3

- name: Pull client Docker image
  docker_image:
    name: joymalanga/yolo-client:v1.0.0
    source: pull
  register: client_image
  tags:
    - client



- name: build client docker container
  docker_container:
    name: yolo-client-container
    image: joymalanga/yolo-client:v1.0.0
    state: started
    volumes:
      - ./client:/app/client/
    ports:
      - '3000:3000'
    networks:
      - name: yolo_network
    network_mode: bridge
