# ---
# - name: Clone the repository from GitHub
#   git:
#     repo: https://github.com/alphaWomanMuthonks/yolo.git
#     dest: "{{playbook_dir}}/client"
#   become: true

# - name: Install Dependencies for client
#   shell: npm install
#   args:
#     chdir: "{{playbook_dir}}/client"

# - name: Start Client 
#   shell: npm start
#   args:
#     chdir: "{{playbook_dir}}/client"
---
- name: Clone the repository from GitHub
  git:
    repo: https://github.com/alphaWomanMuthonks/yolo.git
    dest: "{{playbook_dir}}/client"
  become: true

- name: Install Node.js and npm
  apt:
    name: 
      - nodejs
      - npm
    state: present  
  become: true
  when: ansible_distribution == "Ubuntu"  

- name: Start Client
  service: 
    name: npm start
  become: true

